#!/usr/bin/python3
import cgitb
cgitb.enable(display=1,logdir='/home/jason/log')
import os
import re
import rsa
import sys
import json
import time
import fcntl
import random
import hashlib
import requests
import datetime
from loginProxy import libic_login,login,new_session,get_libic_session,proxies
from diskcache import Cache
import json
import time
import os

user_info_cache = Cache('/home/www/app.BOT/.uinfo_cache')
user_info_cache.eviction_policy='none'
user_info_cache.expire()

def read_user_info(open_id):
    assert open_id.startswith('ou_'), 'Not valid open ID!'
    return user_info_cache.get(open_id)

def consume_queue(queue_name):
    try:
        token_file = f"/home/www/app.TOKEN/token/{queue_name}_tokens.json"
        if not os.path.exists(token_file):
            return False
        with open(token_file,'r+') as f:
            fcntl.flock(f,fcntl.LOCK_EX)
            data = json.load(f)
            if len(data['tokens']) == data['current']:
                data['tokens'] = data['tokens'][1:]
                data['current'] -= 1
                f.seek(0)
                json.dump(data,f)
                f.truncate()
                return True
            else:
                return False
    except Exception as e:
        return False

def consume_token(queue_list):
    queue_list = list(queue_list)
    random.shuffle(queue_list)
    for q in queue_list:
        if consume_queue(q):
            return True
    return False

def badRequest(content = "Invalid parameters"):
    print("Status: 400 Bad Request\nContent-Type: text/html\n\n",end='')
    print(f"<html><body><h1>400 Bad Request</h1><p>{content}</p></body></html>",end='')
    exit()

def success(content):
    print("Status: 200 OK")
    print("Content-Type:Application")
    print(f"Content-Length:{len(content)}")
    print("")
    print(content)
    exit()

def unavailable():
    print("Status: 503 Service Unavailable")
    print("Content-Type: text/html")
    print("")
    print("<html><body><h1>503 Service Unavailable</h1><p>Please try again later.</p></body></html>")
    exit()

status_map = {1    :'预约成功',
              2    :'未开始',
              4    :'已开始',
              #8    :'未缴费',
              16   :'已违约',
              #32   :'已缴费',
              64   :'已签到',
              128  :'已结束',
              256  :'待审核',
              512  :'审核未通过',
              1024 :'审核通过',
              2048 :'已暂离',
              8192 :'待同意'
             }
convert_time = lambda x:time.localtime(x//1000)
class reservation:
    def __init__(self,data):
        self.status=data['resvStatus']
        self.beginTime = convert_time(data['resvBeginTime'])
        self.endTime = convert_time(data['resvEndTime'])
        self.realEndTime = convert_time(data['resvEndRealTime'])
        self.checkTime = convert_time(data['resvCheckTime'])
        self.resvMembers = [i['trueName']+i['logonName'] for i in data['resvMemberInfoList']]
        location = data['resvDevInfoList'][0]
        self.resvID = data['resvID']
        self.uuID = data['uuID']
        self.Location = location['labName']+' '+location['roomName']+' '+location['devName']+' ID:'+location['devID']
    def __str__(self):
        buffer = '预约ID: '+self.resvID+' '
        buffer += f'UUID:{self.uuID}'
        buffer += '状态:'
        for k,v in status_map.items():
            if k&self.status:
                buffer += v+' '
        buffer += time.strftime('%m-%d %H:%M',self.beginTime)+'-'
        buffer += time.strftime('%H:%M',self.endTime)+' '
        buffer += '实际结束:'+time.strftime('%H:%M',self.realEndTime)+' '
        buffer += '预约时间:'+time.strftime('%H:%M',self.checkTime)+' '
        buffer += ','.join(self.resvMembers)+' '
        buffer += self.Location
        return buffer
    def __repr__(self):
        return str(self)

cache = Cache("/home/www/app.LIBIC/.reserve_cache")
cache.size_limit = 5*1024*1024 #5M
cache.eviction_policy = 'least-recently-used'
cache.expire()

def deleteResv(uid,password,uuID):
    if not consume_token(('LIBIC0','LIBIC1','LIBIC2')):unavailable()
    sess,response = get_libic_session(uid,password)
    infos = response.json()['data']
    accountNo = infos['accNo']
    token = infos['token']
    headers = dict(token=token,lan='1')
    data = dict(uuid=uuID)
    response = sess.post('https://libic.nankai.edu.cn/ic-web/reserve/delete',headers=headers,json=data,proxies=proxies).json()
    return json.dumps(dict(msg = response['message']))


if __name__ == "__main__":
    request_method = os.environ.get('REQUEST_METHOD', 'GET')
    if request_method != 'GET':badRequest('Unsupported request')
    request_uri = os.environ.get('REQUEST_URI', '')
    
    headers = dict()
    for key, value in os.environ.items():
        if key.startswith("HTTP_"):
            headers[key[5:].replace('_',' ')] = value

    def get_from_header(name,def_val = None):
        cont = headers.get(name,def_val)
        if cont != def_val and cont.endswith(','):
            return cont[:-1]
        return cont
    openID = get_from_header('OPENID')

    try:
        userID, password = read_user_info(openID)
    except Exception:
        unavailable()

    uuID = get_from_header('UUID')
    if not uuID:
        unavailable()
    success(deleteResv(userID,password,uuID))
