#!/usr/bin/python3
import cgitb
cgitb.enable(display=1,logdir='/home/ubuntu/log')
#from urllib.parse import urlencode,quote
import os
import re
import rsa
import sys
import json
import time
import fcntl
import random
import hashlib
import requests
import datetime
from loginNormal import get_eamis_session
from diskcache import Cache
import html2text
import json
import time
import os

user_info_cache = Cache('/home/www/app.BOT/.uinfo_cache')
user_info_cache.eviction_policy='none'
user_info_cache.expire()

def read_user_info(open_id):
    assert open_id.startswith('ou_'), 'Not valid open ID!'
    return user_info_cache.get(open_id)

def consume_queue(queue_name):
    try:
        token_file = f"/home/www/app.TOKEN/token/{queue_name}_tokens.json"
        if not os.path.exists(token_file):
            return False
        with open(token_file,'r+') as f:
            fcntl.flock(f,fcntl.LOCK_EX)
            data = json.load(f)
            if len(data['tokens']) == data['current']:
                data['tokens'] = data['tokens'][1:]
                data['current'] -= 1
                f.seek(0)
                json.dump(data,f)
                f.truncate()
                return True
            else:
                return False
    except Exception as e:
        return False

def consume_token(queue_list):
    queue_list = list(queue_list)
    random.shuffle(queue_list)
    for q in queue_list:
        if consume_queue(q):
            return True
    return False

def badRequest(content = "Invalid parameters"):
    print("Status: 400 Bad Request\nContent-Type: text/html\n\n",end='')
    print(f"<html><body><h1>400 Bad Request</h1><p>{content}</p></body></html>",end='')
    exit()

def success(content):
    print("Status: 200 OK")
    print("Content-Type:Application")
    print(f"Content-Length:{len(content)}")
    print("")
    print(content)
    exit()

def unavailable():
    print("Status: 503 Service Unavailable")
    print("Content-Type: text/html")
    print("")
    print("<html><body><h1>503 Service Unavailable</h1><p>Please try again later.</p></body></html>")
    exit()


class account:
    def __init__(self,aid,apassword):
        self.ID = aid
        self.PASSWORD = apassword

h = html2text.HTML2Text()
h.ignore_links = True
def readable(content):
    return h.handle(content)

cache = Cache("/home/www/app.EAMIS/.score_cache")
cache.size_limit = 100*1024*1024 #100M
cache.eviction_policy = 'least-recently-used'
cache.expire()

def process(string_input):
    result_string = ''
    pass_semester = None
    for line in string_input.split('\n'):
        if not len(line):
            continue
        res = tuple(map(lambda x:x.strip(),line.split('|')))
        if len(res) < 8:
            if '---' not in line: result_string += line+'\n'
            continue
        if '---' in line or '学年学期' in line:
            continue
        semester, _, _ , name, ctype, credit, sA, sB = res
        if semester != pass_semester:
            year,cnt = semester.split()
            result_string += f'{year}年 第{cnt}学期'
            pass_semester = semester
        result_string += f'{ctype} {name},{credit}学分'
        if sA == sB:
            result_string += sA +'\n'
        elif 'A' in sA or 'B' in sA or 'C' in sA or 'D' in sA or 'E' in sA or 'F' in sA:
            result_string += f'等级{sA},绩点{sB}' + '\n'
        elif '--' in sB:
            result_string += sA +'\n'
        else:
            pass
            #raise NotImplementedError
    return result_string

#@cache.memoize(expire=3*3600)#3hour
def get_tables(uid,password):
    sess,_ = get_eamis_session(uid,password)
    timestamp = str(int(time.time()*1000))
    response = dict()
    sess.get('https://eamis.nankai.edu.cn/eams/home.action')
    url = f'https://eamis.nankai.edu.cn/eams/teach/grade/course/person!historyCourseGrade.action?projectType=MAJOR'
    description = sess.get(url).text
    with open('record','a') as file:
        file.write(description)
    description = readable(description)
    description = process(description)
    response = dict(result=description)
    return json.dumps(response)


if __name__ == "__main__":
    request_method = os.environ.get('REQUEST_METHOD', 'GET')
    if request_method != 'GET':badRequest('Unsupported request')
    request_uri = os.environ.get('REQUEST_URI', '')
    
    headers = dict()
    for key, value in os.environ.items():
        if key.startswith("HTTP_"):
            headers[key[5:].replace('_',' ')] = value

    openID = headers.get('OPENID',None)
    if not openID:
        unavailable()
    if openID[-1] == ',':
        openID = openID[:-1]

    try:
        userID, password = read_user_info(openID)
    except Exception:
        unavailable()

    if len(userID) > 7:
        sucess(json.dumps(dict(result="对不起，暂仅支持本科生")))

    success(get_tables(userID,password))
