#!/usr/bin/python3
from typing import Iterable, Tuple, Dict, List, Callable, Any
import requests
import os
import sys
import time
import json
from diskcache import Cache

tokenDB = Cache('/home/www/app.BOT/.tokenDB')
tokenDB.eviction_policy='none'
tokenDB.expire()

def badRequest(content = "Invalid parameters"):
    print("Status: 400 Bad Request\nContent-Type: text/html\n\n",end='')
    print(f"<html><body><h1>400 Bad Request</h1><p>{content}</p></body></html>",end='')
    exit()

def success(content):
    print("Status: 200 OK")
    print("Content-Type:Application")
    print(f"Content-Length:{len(content)}")
    print("")
    print(content)
    exit()

def unavailable():
    print("Status: 503 Service Unavailable")
    print("Content-Type: text/html")
    print("")
    print("<html><body><h1>503 Service Unavailable</h1><p>Please try again later.</p></body></html>")
    exit()

def readFromDatabase(dataBase:Cache, key:str)->object:
    return dataBase.get(key,None)


def _convertTimestampToTimeString(timeStamp:int)->str:
    """
    Convert a timestamp to a time string.
    :param timeStamp: The timestamp to convert.
    :return: The formatted time string.
    """
    timeStruct = time.localtime(timeStamp)
    return time.strftime('%Y-%m-%d %H:%M',timeStruct)

def _convertTimeStringToTimestamp(timeString:str)->int:
    '''
    Convert a time string to a timestamp.
    :param timeString: The time string to convert.
    :return: The timestamp.
    '''
    try:
        timeStruct = time.strptime(timeString, '%Y-%m-%d %H:%M')
        return int(time.mktime(timeStruct))*1000, False
    except Exception:pass
    try:
        timeStruct = time.strptime(timeString, '%Y-%m-%d')
        return int(time.mktime(timeStruct))*1000, True
    except Exception:pass
    raise Exception(f'Cannot parse time format, should be either %Y-%m-%d or %Y-%m-%d %H:%M, got {timeString} instead')

session = requests.Session()
def _generateHeader(openID) -> Dict[str, str]:
    """
    Generate headers for the request.
    :return: A dictionary of headers.
    """
    token = _getAccessToken(openID)
    return {'Content-Type': 'application/json; charset=utf-8',
            'Authorization': 'Bearer '+token}

def _getAccessToken(openID):
    curInfo = readFromDatabase(tokenDB,openID)
    if curInfo is None:
        raise Exception('No token found')
    accessToken = curInfo.get('accessToken','')
    return accessToken

def _inferUidType(uid: str) -> str:
    """
    Infer the type of a user ID.
    :param uid: The user ID to infer the type of.
    :return: The type of the user ID ('openID', 'unionID', or 'userID').
    """
    if uid.startswith('ou_'):
        return 'open_id'
    elif uid.startswith('on_'):
        return 'union_id'
    else:
        return 'user_id'

def _getOpenID(userID:str,redundant:bool=False)->str:
    """
    Convert a user ID to an OpenID.
    :param userID: The user ID to convert.
    :param redundant: If True, return also user's name and employee number.
    :return: The OpenID corresponding to the user ID.
    """
    url = f'https://open.feishu.cn/open-apis/contact/v3/users/{userID}'
    id_type = _inferUidType(userID)
    params = dict(user_id_type=id_type,department_id_type='department_id')
    res = requests.get(url,params=params,headers=_generateHeader()).json()
    if res['msg'] != 'success':
        raise ValueError(f"Error: {res['msg']}")
    if redundant:
        userName = res['data']['user'].get('name','UNKNOWN')
        employeeNumber = res['data']['user'].get('employee_no','UNKNOWN')
        return res['data']['user']['open_id'], userName, employeeNumber
    return res['data']['user']['open_id']

OPENAPI_URL = "https://open.feishu.cn/open-apis"

def _timeInfoToStr(timePoint)->str:
    timePointVal = int(timePoint['timestamp'])/1000
    timeStruct = time.localtime(timePointVal)
    if 'is_all_day' in timePoint:
        return time.strftime('%Y-%m-%d', timeStruct)
    else:
        return time.strftime('%Y-%m-%d %H:%M',timeStruct)
    raise ValueError('Invalid time info format')

session = requests.session()

def _listAllTasks(openID:str, filterComplete:bool=None):
    assert filterComplete in (True, False, None)
    headers = _generateHeader(openID)
    cururl = f'{OPENAPI_URL}/task/v2/tasks'
    buffer = list()
    hasMore = True; pageToken = None
    params = dict(page_size = 5,
                  type = 'my_tasks',
                  user_id_type = 'user_id')
    if filterComplete is not None:
        params['completed'] = filterComplete
    while hasMore:
        if pageToken: params['page_token'] = pageToken
        result = session.get(cururl, headers=headers, params=params).json()
        if result['code']:
            raise Exception(result['msg'])
        buffer.extend(result['data']['items'])
        hasMore = result['data']['has_more']
        pageToken = result['data'].get('page_token',None)
    
    def expressTask(task)->dict:
        result = dict()
        result['guid'] = task['guid']
        result['summary'] = task['summary']
        if task.get('description',''):
            result['description'] = task['description']
        if 'due' in result:
            result['due'] = _timeInfoToStr(task['due'])
        if 'completed_at' in task:
            result['completed_at'] = time.strftime('%Y-%m-%d %H:%M', time.localtime(int(task['completed_at'])/1000))
        result['status'] = task['status']
        if 'start' in task:
            result['start'] = _timeInfoToStr(task['start'])
        return result

    def taskToStr(taskDict)->str:
        buffer = taskDict['summary'] + f'(GUID:{taskDict["guid"]})'
        if 'description' in taskDict:
            buffer += f' {taskDict["description"]}'
        if taskDict['status'] == 'done':
            buffer += f' 在{taskDict["completed_at"]}完成'
        else:
            if 'due' in taskDict:
                buffer += f' 未完成:{taskDict["due"]}截止'
            else:
                buffer += ' 未完成'
            if 'start' in taskDict:
                buffer += f' {taskDict["start"]}开始'
        return buffer

    return [taskToStr(expressTask(task)) for task in buffer]

def _createTask(openID:str, summary:str, **taskDetail)->str:
    try:
        headers = _generateHeader(openID)
        params = dict(user_id_type='open_id')
        curURL = f'{OPENAPI_URL}/task/v2/tasks'
        body = dict(summary = summary)
        if 'due' in taskDetail:
            timestamp, is_all_day = _convertTimeStringToTimestamp(taskDetail['due'])
            body['due'] = dict(timestamp=timestamp, is_all_day=is_all_day)
        if 'description' in taskDetail:
            body['description'] = taskDetail['description']
        if 'start' in taskDetail:
            timestamp, is_all_day = _convertTimeStringToTimestamp(taskDetail['start'])
            body['start'] = dict(timestamp=timestamp, is_all_day=is_all_day)
        body['origin'] = dict(platform_i18n_name=dict(zh_cn='喵学姐', en_us='Meow Senpai'))
        body['members'] = [dict(id=openID,
                                type='user',
                                role='assignee'),]
        res = session.post(curURL,params=params, headers=headers, json=body).json()
    except Exception as e:
        return str(e)
    if res['code']:
        return res['msg']
    else:
        return res['data']['task']['guid']

def _updateTask(openID:str, guid:str, **detail)->str:
    curURL = f'{OPENAPI_URL}/task/v2/tasks/{guid}'
    headers = _generateHeader(openID)
    params = dict(user_id_type='user_id')
    task = dict(); fields=list()
    if 'summary' in detail:
        task['summary'] = detail['summary']
        fields.append('summary')
    if 'description' in detail:
        task['description'] = detail['description']
        fields.append('description')
    if 'due' in detail:
        fields.append('due')
        if 'none' not in detail['due'].lower():
            timestamp, is_all_day = _convertTimeStringToTimestamp(detail['due'])
            task['due'] = dict(timestamp=timestamp, is_all_day=is_all_day)
    if 'start' in detail:
        fields.append('start')
        if 'none' not in detail['start'].lower():
            timestamp, is_all_day = _convertTimeStringToTimestamp(detail['start'])
            task['start'] = dict(timestamp=timestamp, is_all_day=is_all_day)
    if 'hasCompleted' in detail:
        fields.append('completed_at')
        if detail['hasCompleted'] == True:
            task['completed_at'] = str(int(1000*time.time()))
        elif detail['hasCompleted'] == False:
            task['completed_at'] = '0'
    body = dict(task=task, update_fields=fields)
    if not fields:
        return dict(msg='无更新项目')
    res = session.patch(curURL, params=params, headers=headers, json=body).json()
    if res['code']:
        errorMsg = res['msg']
        if 'cannot set non-zero completed_at for a completed task' in res['msg']:
            return '任务已经完成，无需再次完成'
        return res['msg']
    else:
        return 'success'

def _deleteTask(openID:str, guid:str)->str:
    curURL = f'{OPENAPI_URL}/task/v2/tasks/{guid}'
    headers = _generateHeader(openID)
    res = session.delete(curURL, headers=headers).json()
    if res['code']:
        return res['msg']
    else:
        return res['msg'] or 'success'

if __name__ == '__main__':
    request_method = os.environ.get('REQUEST_METHOD', 'GET')
    if request_method != 'DELETE':badRequest('Unsupported request')
    request_uri = os.environ.get('REQUEST_URI', '')

    headers = dict()
    for key, value in os.environ.items():
        if key.startswith("HTTP_"):
            headers[key[5:].replace('_',' ')] = value

    def get_from_header(name,def_val = None):
        cont = headers.get(name,def_val)
        if cont != def_val and cont.endswith(','):
            return cont[:-1]
        return cont

    GUID = get_from_header('GUID')
    openID = get_from_header('OPENID')
    token = get_from_header('TOKEN',None)
    if token: _getAccessToken = lambda _: token
    try:
        res = _deleteTask(openID, GUID)
    except Exception as e:
        success(json.dumps(dict(result=str(e))))
    success(json.dumps(dict(result = str(res))))
